@hostname = localhost
@port = {{$dotenv PORT}}
@baseURL = http://{{hostname}}:{{port}}/api





















##### ADMIN ROUTES ####
#
#
#
@adminID = 623741957f8e2a1160c4cf2c
###
# @name GET_ALL_ADMINS
GET {{baseURL}}/admins
####################################################
# @name GET_ADMIN_BY_ID
GET {{baseURL}}/admins/{{adminID}} 
####################################################
# @name CREATE_ADMIN
POST {{baseURL}}/admins/create
Content-Type: application/json

{
  "emailAddress": "ilechuks73@gmail.com",
  "firstName": "joshua",
  "lastName": "ilechukwu",
  "gender": "male",
  "homeAddress": "home address",
  "maritalStatus": "single",
  "password": "password"
}
####################################################
# @name SIGNIN
POST {{baseURL}}/admins/signin
Content-Type: application/json

{
  "emailAddress": "ilechuks73@gmail.com",
  "password": "password"
}
####################################################
# @name DELETE
DELETE {{baseURL}}/admins/{{adminID}}















##### USER ROUTES ##############
#
#
#
@userID = 62376bfe387b34f60d2bbf40
###
# @name getAllUsers
GET {{baseURL}}/users
###
# @name getUserByID

GET {{baseURL}}/users/{{userID}}
###
# @name signup
POST {{baseURL}}/users/signup 
Content-Type: application/json

{
  "emailAddress": "amarkumargta@gmail.com",
  "firstName": "Amartya",
  "lastName": "kumar",
  "gender": "male",
  "homeAddress": "home address",
  "maritalStatus": "single",
  "password": "password"
}
###
# @name signin
POST {{baseURL}}/users/signin 
Content-Type: application/json

{
  "emailAddress": "ilechuks@gmail.com",
  "password": "password"
}
###
# @name deactivate
GET {{baseURL}}/users/acti









##### PRDOUCT ROUTES ##############
#
#
#

###

# @name getAllProducts
GET {{baseURL}}/products 

###

# @name getProductByID
@productID = product1
GET {{baseURL}}/products/{{productID}}
